all: Participation

Participation: day2Starter.cpp day2Starter_implementation.cpp day2Starter.h
	g++ -g -Wall -std=c++11 day2Starter.cpp day2Starter_implementation.cpp -o outputExecutable
	./outputExecutable