all: Participation

Participation: package_report.cpp package_report_implementation.cpp package_report.h
	g++ -g -Wall -std=c++11 package_report.cpp package_report_implementation.cpp -o outputExecutable
	./outputExecutable