all: Dart_Game

Dart_Game: Dart_Game.cpp Dart_Game_Implementation.cpp header.h
	@g++ -g -Wall -std=c++11 Dart_Game.cpp Dart_Game_Implementation.cpp -o outputExecutable
	@./outputExecutable
	@rm ./outputExecutable