all: Wizard_Game

Wizard_Game: wizard_game.cpp wizard_game_implementation.cpp header.h
	@g++ -g -Wall -std=c++11 wizard_game.cpp wizard_game_implementation.cpp -o outputExecutable
	@./outputExecutable
	@rm ./outputExecutable