all: Wizard_Game

Wizard_Game: sw_tcw_game.cpp sw_tcw_implementation.cpp header.h
	@g++ -g -Wall -std=c++11 sw_tcw_game.cpp sw_tcw_implementation.cpp -o outputExecutable
	@./outputExecutable
	@rm ./outputExecutable